version: "3"

volumes:
  db:
    external: false

services:
  frontend:
    build: ./frontend/
    restart: always
    ports:
      - "80:80"
    links:
      - backend

  backend:
    build: ./backend/
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    image: "mongo"
    restart: always
    volumes:
      - db:/data/db

